export const actionTypes = {
    ADD_POST:"ADD_POST",
    GET_POSTS:"GET_POSTS",
    GET_COMMENT:"GET_COMMENT",
    ADD_COMMENT:"ADD_COMMENT",
    DELETE_COMMENT:"DELETE_COMMENT",
    EDIT_COMMENT:"EDIT_COMMENT",
    GET_TOPIC : "GET_TOPIC",
    GET_USERS : "GET_USERS",
    GET_USER : "GET_USER",
    PAGE_COUNT : "PAGE_COUNT",
    CHANGE_PAGE:"PAGE_CHANGE",
}