export const actionTypes = {
    ADD_POST:"ADD_POST",
    GET_POSTS:"GET_POSTS",
    GET_COMMENT:"GET_COMMENT",
    ADD_COMMENT:"ADD_COMMENT",
    DELETE_COMMENT:"DELETE_COMMENT",
    GET_TOPIC : "GET_TOPIC"
}